import {Routes} from '@angular/router';
import {Landing} from './componente/landing/landing';
import {MenuAnfitrion} from './componente/menu-anfitrion/menu-anfitrion';
import {Legal} from './componente/legal/legal';
import {Configuracion} from './componente/configuracion/configuracion';
import {CentroAyuda} from './componente/centro-ayuda/centro-ayuda';
import {Register} from './componente/register/register';
import {RegisterAnfitrion} from './componente/register-anfitrion/register-anfitrion';
import {RegisterProveedor} from './componente/register-proveedor/register-proveedor';
import {Login} from './componente/login/login';
import {RegisterCaptcha} from './componente/register-captcha/register-captcha';
import {MenuProveedor} from './componente/menu-proveedor/menu-proveedor';
import {CrearEvento} from './componente/crear-evento/crear-evento';
import {ComunicateConNosotros} from './componente/comunicate-con-nosotros/comunicate-con-nosotros';
import {VerMiPerfil} from './componente/ver-mi-perfil/ver-mi-perfil';
import {Administrador} from './componente/administrador/administrador';
import {BuscarEventos} from './componente/buscar-eventos/buscar-eventos';
import {HistorialDeEventos} from './componente/historial-de-eventos/historial-de-eventos';
import {ListarEvento} from './componente/listar-evento/listar-evento';
import {DetalleDeEvento} from './componente/detalle-de-evento/detalle-de-evento';
import {ConfirmarReserva} from './componente/confirmar-reserva/confirmar-reserva';
import {EventosCurso} from './componente/eventos-curso/eventos-curso';
import {EdicionDeResenas} from './componente/edicion-de-resenas/edicion-de-resenas';
import {HistorialDeContratos} from './componente/historial-de-contratos/historial-de-contratos';
import {ReporteProveedores} from './componente/reporte-proveedor/reporte-proveedores';

export const routes: Routes = [
  {path: '', component: Landing},
  {path: 'menu-anfitrion/:id', component: MenuAnfitrion},
  {path: 'legal/:id/:role', component: Legal},
  {path: 'configuracion/:id/:role', component: Configuracion},
  {path: 'centro-ayuda/:id/:role', component: CentroAyuda},
  {path: 'register', component: Register},
  {path: 'register-anfitrion', component: RegisterAnfitrion},
  {path: 'register-proveedor', component: RegisterProveedor},
  {path: 'login', component: Login},
  {path: 'register-captcha', component: RegisterCaptcha},
  {path: 'menu-proveedor/:id', component: MenuProveedor},
  {path: 'crear-evento/proveedor/:idProveedor', component: CrearEvento},
  {path: 'crear-evento/evento/:idProveedor/:idEvento', component: CrearEvento},
  {path: 'comunicate-con-nosotros/:id/:role', component: ComunicateConNosotros},
  {path: 'ver-mi-perfil/:id/:role', component: VerMiPerfil},
  {path: 'administrador', component: Administrador},
  {path: 'buscar-eventos/:id', component: BuscarEventos},
  {path: 'historial-eventos/:id', component: HistorialDeEventos},
  {path: 'historial-contratos/:id', component: HistorialDeContratos},
  {path: 'listar-eventos/:id', component: ListarEvento},
  {path: 'detalle-eventos/:idAnfitrion/:idEvento', component: DetalleDeEvento},
  {path: 'reservar-evento/:idAnfitrion/:idEvento', component: ConfirmarReserva},
  {path: 'eventos-curso/:id', component: EventosCurso},
  {path: 'edicion-resena/:idAnfitrion/:idEvento', component: EdicionDeResenas},
  {path: 'reporte-proveedor/:id', component: ReporteProveedores},
];
